#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 18 11:10:07 2017

@author: yajun
"""


import pandas as pd
from numpy  import *
from pymongo import *
import json

client = MongoClient()
client = MongoClient("mongodb://192.168.10.60:27017/")
db = client.stocks

cash_flow_items = 'qfa_cash_recp_sg_and_rs,qfa_recp_tax_rends,qfa_other_cash_recp_ral_oper_act,qfa_net_incr_insured_dep,qfa_net_incr_dep_cob,qfa_net_incr_loans_central_bank,qfa_net_incr_fund_borr_ofi,qfa_net_incr_int_handling_chrg,qfa_cash_recp_prem_orig_inco,qfa_net_cash_received_reinsu_bus,qfa_net_incr_disp_tfa,qfa_net_incr_disp_fin_assets_avail,qfa_net_incr_loans_other_bank,qfa_net_incr_repurch_bus_fund,qfa_stot_cash_inflows_oper_act,qfa_cash_pay_goods_purch_serv_rec,qfa_cash_pay_beh_empl,qfa_pay_all_typ_tax,qfa_other_cash_pay_ral_oper_act,qfa_net_incr_clients_loan_adv,qfa_net_incr_dep_cbob,qfa_cash_pay_claims_orig_inco,qfa_handling_chrg_paid,qfa_comm_insur_plcy_paid,qfa_stot_cash_outflows_oper_act,qfa_net_cash_flows_oper_act,qfa_cash_recp_disp_withdrwl_invest,qfa_cash_recp_return_invest,qfa_net_cash_recp_disp_fiolta,qfa_net_cash_recp_disp_sobu,qfa_other_cash_recp_ral_inv_act,qfa_stot_cash_inflows_inv_act,qfa_cash_pay_acq_const_fiolta,qfa_cash_paid_invest,qfa_net_incr_pledge_loan,qfa_net_cash_pay_aquis_sobu,qfa_other_cash_pay_ral_inv_act,qfa_stot_cash_outflows_inv_act,qfa_net_cash_flows_inv_act,qfa_cash_recp_cap_contrib,qfa_cash_rec_saims,qfa_cash_recp_borrow,qfa_other_cash_recp_ral_fnc_act,qfa_proc_issue_bonds,qfa_stot_cash_inflows_fnc_act,qfa_cash_prepay_amt_borr,qfa_cash_pay_dist_dpcp_int_exp,qfa_dvd_profit_paid_sc_ms,qfa_other_cash_pay_ral_fnc_act,qfa_stot_cash_outflows_fnc_act,qfa_net_cash_flows_fnc_act,qfa_eff_fx_flu_cash,qfa_net_incr_cash_cash_equ_dm,qfa_cash_cash_equ_end_period,qfa_net_profit_cs,qfa_prov_depr_assets,qfa_depr_fa_coga_dpba,qfa_amort_intang_assets,qfa_amort_lt_deferred_exp,qfa_decr_deferred_exp,qfa_incr_acc_exp,qfa_loss_disp_fiolta,qfa_loss_scr_fa,qfa_loss_fv_chg,qfa_fin_exp_cs,qfa_invest_loss,qfa_deferred_tax_assets_decr,qfa_incr_deferred_inc_tax_liab,qfa_decr_inventories,qfa_decr_oper_payable,qfa_incr_oper_payable,qfa_unconfirmed_invest_loss_cs,qfa_others,qfa_im_net_cash_flows_oper_act,qfa_conv_debt_into_cap,qfa_conv_corp_bonds_due_within_1y,qfa_fa_fnc_leases,qfa_end_bal_cash,qfa_end_bal_cash_equ,qfa_net_incr_cash_cash_equ_im'
operation_act_cf = 'QFA_CASH_RECP_SG_AND_RS,QFA_RECP_TAX_RENDS,QFA_OTHER_CASH_RECP_RAL_OPER_ACT,QFA_NET_INCR_INSURED_DEP,QFA_NET_INCR_DEP_COB,QFA_NET_INCR_LOANS_CENTRAL_BANK,QFA_NET_INCR_FUND_BORR_OFI,QFA_NET_INCR_INT_HANDLING_CHRG,QFA_CASH_RECP_PREM_ORIG_INCO,QFA_NET_CASH_RECEIVED_REINSU_BUS,QFA_NET_INCR_DISP_TFA,QFA_NET_INCR_DISP_FIN_ASSETS_AVAIL,QFA_NET_INCR_LOANS_OTHER_BANK,QFA_NET_INCR_REPURCH_BUS_FUND,QFA_STOT_CASH_INFLOWS_OPER_ACT,QFA_CASH_PAY_GOODS_PURCH_SERV_REC,QFA_CASH_PAY_BEH_EMPL,QFA_PAY_ALL_TYP_TAX,QFA_OTHER_CASH_PAY_RAL_OPER_ACT,QFA_NET_INCR_CLIENTS_LOAN_ADV,QFA_NET_INCR_DEP_CBOB,QFA_CASH_PAY_CLAIMS_ORIG_INCO,QFA_HANDLING_CHRG_PAID,QFA_COMM_INSUR_PLCY_PAID,QFA_STOT_CASH_OUTFLOWS_OPER_ACT,QFA_NET_CASH_FLOWS_OPER_ACT'

investing_act_cf = 'QFA_CASH_RECP_DISP_WITHDRWL_INVEST,QFA_CASH_RECP_RETURN_INVEST,QFA_NET_CASH_RECP_DISP_FIOLTA,QFA_NET_CASH_RECP_DISP_SOBU,QFA_OTHER_CASH_RECP_RAL_INV_ACT,QFA_STOT_CASH_INFLOWS_INV_ACT,QFA_CASH_PAY_ACQ_CONST_FIOLTA,QFA_CASH_PAID_INVEST,QFA_NET_INCR_PLEDGE_LOAN,QFA_NET_CASH_PAY_AQUIS_SOBU,QFA_OTHER_CASH_PAY_RAL_INV_ACT,QFA_STOT_CASH_OUTFLOWS_INV_ACT,QFA_NET_CASH_FLOWS_INV_ACT'

financial_act_cf = 'QFA_CASH_RECP_CAP_CONTRIB,QFA_CASH_REC_SAIMS,QFA_CASH_RECP_BORROW,QFA_OTHER_CASH_RECP_RAL_FNC_ACT,QFA_PROC_ISSUE_BONDS,QFA_STOT_CASH_INFLOWS_FNC_ACT,QFA_CASH_PREPAY_AMT_BORR,QFA_CASH_PAY_DIST_DPCP_INT_EXP,QFA_DVD_PROFIT_PAID_SC_MS,QFA_OTHER_CASH_PAY_RAL_FNC_ACT,QFA_STOT_CASH_OUTFLOWS_FNC_ACT,QFA_NET_CASH_FLOWS_FNC_ACT'
#'QFA_TOT_OPER_REV,QFA_OPER_REV,QFA_INTEREST_INC,QFA_INSUR_PREM_UNEARNED,QFA_HANDLING_CHRG_COMM_INC,QFA_TOT_PREM_INC,QFA_REINSUR_INC,QFA_PREM_CEDED,QFA_UNEARNED_PREM_RSRV,QFA_NET_INC_AGENCY BUSINESS,QFA_NET_INC_UNDERWRITING-BUSINESS,QFA_NET_INC_CUSTOMERASSET-MANAGEMENT BUSINESS,QFA_OTHER_OPER_INC,QFA_NET_INT_INC,QFA_NET_FEE_AND_COMMISSION_INC,QFA_NET_OTHER_OPER_INC,QFA_TOT_OPER_COST,QFA_OPER_COST,QFA_GROSSMARGIN,QFA_INTEREST_EXP,QFA_HANDLING_CHRG_COMM_EXP,QFA_OPER_EXP,QFA_TAXES_SURCHARGES_OPS,QFA_SELLING_DIST_EXP,QFA_GERL_ADMIN_EXP,QFA_FIN_EXP_IS,QFA_IMPAIR_LOSS_ASSETS,QFA_PREPAY_SURR,QFA_NET_CLAIM_EXP,QFA_NET_INSUR_CONT_RSRV,QFA_DVD_EXP_INSURED,QFA_REINSURANCE_EXP,QFA_CLAIM_EXP_RECOVERABLE,QFA_INSUR_RSRV_RECOVERABLE,QFA_REINSUR_EXP_RECOVERABLE,QFA_OTHER_OPER_EXP,QFA_NET_GAIN_CHG_FV,QFA_NET_INVEST_INC,QFA_INC_INVEST_ASSOC_JV_ENTP,QFA_NET_GAIN_FX_TRANS,QFA_OPPROFIT,QFA_NON_OPER_REV,QFA_NON_OPER_EXP,QFA_NET_LOSS_DISP_NONCUR_ASSET,QFA_TOT_PROFIT,QFA_TAX,QFA_UNCONFIRMED_INVEST_LOSS_IS,QFA_NET_PROFIT_IS,QFA_MINORITY_INT_INC,QFA_NP_BELONGTO_PARCOMSH,QFA_OTHER_COMPREH_INC,QFA_TOT_COMPREH_INC,QFA_TOT_COMPREH_INC_MIN_SHRHLDR,QFA_TOT_COMPREH_INC_PARENT_COMP'
#    print("QFA_NET_CASH_FLOWS_INV_ACT_R[\'" + ss +"_R\'] = " + "data[\'"+ss+"\'] / "+"data['QFA_NET_CASH_FLOWS_INV_ACT']")
def QFA_NET_CASH_FLOWS_FNC_ACT_R():
    cols = financial_act_cf
    input_data = db.bond_season_cashflow
    data = pd.DataFrame(list(input_data.find()))
    
    
    
    for ss in cols.split(','):
        print("QFA_NET_CASH_FLOWS_FNC_ACT_R[\'" + ss +"_R\'] = " + "data[\'"+ss+"\'] / "+"data['QFA_NET_CASH_FLOWS_FNC_ACT']")
    
      
    QFA_NET_CASH_FLOWS_FNC_ACT_R = pd.DataFrame()
    QFA_NET_CASH_FLOWS_FNC_ACT_R['code'] = data['code'] 
    QFA_NET_CASH_FLOWS_FNC_ACT_R['rptDate'] = data['rptDate']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_CASH_RECP_CAP_CONTRIB_R'] = data['QFA_CASH_RECP_CAP_CONTRIB'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_CASH_REC_SAIMS_R'] = data['QFA_CASH_REC_SAIMS'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_CASH_RECP_BORROW_R'] = data['QFA_CASH_RECP_BORROW'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_OTHER_CASH_RECP_RAL_FNC_ACT_R'] = data['QFA_OTHER_CASH_RECP_RAL_FNC_ACT'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_PROC_ISSUE_BONDS_R'] = data['QFA_PROC_ISSUE_BONDS'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_STOT_CASH_INFLOWS_FNC_ACT_R'] = data['QFA_STOT_CASH_INFLOWS_FNC_ACT'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_CASH_PREPAY_AMT_BORR_R'] = data['QFA_CASH_PREPAY_AMT_BORR'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_CASH_PAY_DIST_DPCP_INT_EXP_R'] = data['QFA_CASH_PAY_DIST_DPCP_INT_EXP'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_DVD_PROFIT_PAID_SC_MS_R'] = data['QFA_DVD_PROFIT_PAID_SC_MS'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_OTHER_CASH_PAY_RAL_FNC_ACT_R'] = data['QFA_OTHER_CASH_PAY_RAL_FNC_ACT'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_STOT_CASH_OUTFLOWS_FNC_ACT_R'] = data['QFA_STOT_CASH_OUTFLOWS_FNC_ACT'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    QFA_NET_CASH_FLOWS_FNC_ACT_R['QFA_NET_CASH_FLOWS_FNC_ACT_R'] = data['QFA_NET_CASH_FLOWS_FNC_ACT'] / data['QFA_NET_CASH_FLOWS_FNC_ACT']
    
    insert_record = json.loads(QFA_NET_CASH_FLOWS_FNC_ACT_R.to_json(orient='records'))
    ret = db.QFA_NET_CASH_FLOWS_FNC_ACT_R.insert_many(insert_record)
    print(ret)





def QFA_NET_CASH_FLOWS_INV_ACT_R():
    input_data = db.bond_season_cashflow
    data = pd.DataFrame(list(input_data.find()))
    
    
    cols = investing_act_cf
    for ss in cols.split(','):
        print("QFA_NET_CASH_FLOWS_INV_ACT_R[\'" + ss +"_R\'] = " + "data[\'"+ss+"\'] / "+"data['QFA_NET_CASH_FLOWS_INV_ACT']")
    
      
    QFA_NET_CASH_FLOWS_INV_ACT_R = pd.DataFrame()
    QFA_NET_CASH_FLOWS_INV_ACT_R['code'] = data['code'] 
    QFA_NET_CASH_FLOWS_INV_ACT_R['rptDate'] = data['rptDate']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_CASH_RECP_DISP_WITHDRWL_INVEST_R'] = data['QFA_CASH_RECP_DISP_WITHDRWL_INVEST'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_CASH_RECP_RETURN_INVEST_R'] = data['QFA_CASH_RECP_RETURN_INVEST'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_NET_CASH_RECP_DISP_FIOLTA_R'] = data['QFA_NET_CASH_RECP_DISP_FIOLTA'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_NET_CASH_RECP_DISP_SOBU_R'] = data['QFA_NET_CASH_RECP_DISP_SOBU'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_OTHER_CASH_RECP_RAL_INV_ACT_R'] = data['QFA_OTHER_CASH_RECP_RAL_INV_ACT'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_STOT_CASH_INFLOWS_INV_ACT_R'] = data['QFA_STOT_CASH_INFLOWS_INV_ACT'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_CASH_PAY_ACQ_CONST_FIOLTA_R'] = data['QFA_CASH_PAY_ACQ_CONST_FIOLTA'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_CASH_PAID_INVEST_R'] = data['QFA_CASH_PAID_INVEST'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_NET_INCR_PLEDGE_LOAN_R'] = data['QFA_NET_INCR_PLEDGE_LOAN'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_NET_CASH_PAY_AQUIS_SOBU_R'] = data['QFA_NET_CASH_PAY_AQUIS_SOBU'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_OTHER_CASH_PAY_RAL_INV_ACT_R'] = data['QFA_OTHER_CASH_PAY_RAL_INV_ACT'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_STOT_CASH_OUTFLOWS_INV_ACT_R'] = data['QFA_STOT_CASH_OUTFLOWS_INV_ACT'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    QFA_NET_CASH_FLOWS_INV_ACT_R['QFA_NET_CASH_FLOWS_INV_ACT_R'] = data['QFA_NET_CASH_FLOWS_INV_ACT'] / data['QFA_NET_CASH_FLOWS_INV_ACT']
    insert_record = json.loads(QFA_NET_CASH_FLOWS_INV_ACT_R.to_json(orient='records'))
    ret = db.QFA_NET_CASH_FLOWS_INV_ACT_R.insert_many(insert_record)
    print(ret)



def QFA_NET_CASH_FLOWS_OPER_ACT_R():
    input_data = db.bond_season_cashflow
    data = pd.DataFrame(list(input_data.find()))
    
    
    cols = operation_act_cf
    for ss in cols.split(','):
        print("QFA_NET_CASH_FLOWS_OPER_ACT_R[\'" + ss +"_R\'] = " + "data[\'"+ss+"\'] / "+"data['QFA_NET_CASH_FLOWS_OPER_ACT']")
      
    QFA_NET_CASH_FLOWS_OPER_ACT_R = pd.DataFrame()
    QFA_NET_CASH_FLOWS_OPER_ACT_R['code'] = data['code'] 
    QFA_NET_CASH_FLOWS_OPER_ACT_R['rptDate'] = data['rptDate']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_CASH_RECP_SG_AND_RS_R'] = data['QFA_CASH_RECP_SG_AND_RS'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_RECP_TAX_RENDS_R'] = data['QFA_RECP_TAX_RENDS'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_OTHER_CASH_RECP_RAL_OPER_ACT_R'] = data['QFA_OTHER_CASH_RECP_RAL_OPER_ACT'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_INSURED_DEP_R'] = data['QFA_NET_INCR_INSURED_DEP'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_DEP_COB_R'] = data['QFA_NET_INCR_DEP_COB'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_LOANS_CENTRAL_BANK_R'] = data['QFA_NET_INCR_LOANS_CENTRAL_BANK'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_FUND_BORR_OFI_R'] = data['QFA_NET_INCR_FUND_BORR_OFI'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_INT_HANDLING_CHRG_R'] = data['QFA_NET_INCR_INT_HANDLING_CHRG'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_CASH_RECP_PREM_ORIG_INCO_R'] = data['QFA_CASH_RECP_PREM_ORIG_INCO'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_CASH_RECEIVED_REINSU_BUS_R'] = data['QFA_NET_CASH_RECEIVED_REINSU_BUS'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_DISP_TFA_R'] = data['QFA_NET_INCR_DISP_TFA'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_DISP_FIN_ASSETS_AVAIL_R'] = data['QFA_NET_INCR_DISP_FIN_ASSETS_AVAIL'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_LOANS_OTHER_BANK_R'] = data['QFA_NET_INCR_LOANS_OTHER_BANK'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_REPURCH_BUS_FUND_R'] = data['QFA_NET_INCR_REPURCH_BUS_FUND'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_STOT_CASH_INFLOWS_OPER_ACT_R'] = data['QFA_STOT_CASH_INFLOWS_OPER_ACT'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_CASH_PAY_GOODS_PURCH_SERV_REC_R'] = data['QFA_CASH_PAY_GOODS_PURCH_SERV_REC'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_CASH_PAY_BEH_EMPL_R'] = data['QFA_CASH_PAY_BEH_EMPL'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_PAY_ALL_TYP_TAX_R'] = data['QFA_PAY_ALL_TYP_TAX'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_OTHER_CASH_PAY_RAL_OPER_ACT_R'] = data['QFA_OTHER_CASH_PAY_RAL_OPER_ACT'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_CLIENTS_LOAN_ADV_R'] = data['QFA_NET_INCR_CLIENTS_LOAN_ADV'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_INCR_DEP_CBOB_R'] = data['QFA_NET_INCR_DEP_CBOB'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_CASH_PAY_CLAIMS_ORIG_INCO_R'] = data['QFA_CASH_PAY_CLAIMS_ORIG_INCO'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_HANDLING_CHRG_PAID_R'] = data['QFA_HANDLING_CHRG_PAID'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_COMM_INSUR_PLCY_PAID_R'] = data['QFA_COMM_INSUR_PLCY_PAID'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_STOT_CASH_OUTFLOWS_OPER_ACT_R'] = data['QFA_STOT_CASH_OUTFLOWS_OPER_ACT'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    QFA_NET_CASH_FLOWS_OPER_ACT_R['QFA_NET_CASH_FLOWS_OPER_ACT_R'] = data['QFA_NET_CASH_FLOWS_OPER_ACT'] / data['QFA_NET_CASH_FLOWS_OPER_ACT']
    insert_record = json.loads(QFA_NET_CASH_FLOWS_OPER_ACT_R.to_json(orient='records'))
    ret = db.QFA_NET_CASH_FLOWS_OPER_ACT_R.insert_many(insert_record)
    print(ret)

def QFA_TOT_OPER_REV_R():
    input_data = db.bond_season_profit
    data = pd.DataFrame(list(input_data.find()))
    
    #'QFA_TOT_OPER_REV,QFA_OPER_REV,QFA_INTEREST_INC,QFA_INSUR_PREM_UNEARNED,QFA_HANDLING_CHRG_COMM_INC,QFA_TOT_PREM_INC,QFA_REINSUR_INC,QFA_PREM_CEDED,QFA_UNEARNED_PREM_RSRV,QFA_NET_INC_AGENCY BUSINESS,QFA_NET_INC_UNDERWRITING-BUSINESS,QFA_NET_INC_CUSTOMERASSET-MANAGEMENT BUSINESS,QFA_OTHER_OPER_INC,QFA_NET_INT_INC,QFA_NET_FEE_AND_COMMISSION_INC,QFA_NET_OTHER_OPER_INC,QFA_TOT_OPER_COST,QFA_OPER_COST,QFA_GROSSMARGIN,QFA_INTEREST_EXP,QFA_HANDLING_CHRG_COMM_EXP,QFA_OPER_EXP,QFA_TAXES_SURCHARGES_OPS,QFA_SELLING_DIST_EXP,QFA_GERL_ADMIN_EXP,QFA_FIN_EXP_IS,QFA_IMPAIR_LOSS_ASSETS,QFA_PREPAY_SURR,QFA_NET_CLAIM_EXP,QFA_NET_INSUR_CONT_RSRV,QFA_DVD_EXP_INSURED,QFA_REINSURANCE_EXP,QFA_CLAIM_EXP_RECOVERABLE,QFA_INSUR_RSRV_RECOVERABLE,QFA_REINSUR_EXP_RECOVERABLE,QFA_OTHER_OPER_EXP,QFA_NET_GAIN_CHG_FV,QFA_NET_INVEST_INC,QFA_INC_INVEST_ASSOC_JV_ENTP,QFA_NET_GAIN_FX_TRANS,QFA_OPPROFIT,QFA_NON_OPER_REV,QFA_NON_OPER_EXP,QFA_NET_LOSS_DISP_NONCUR_ASSET,QFA_TOT_PROFIT,QFA_TAX,QFA_UNCONFIRMED_INVEST_LOSS_IS,QFA_NET_PROFIT_IS,QFA_MINORITY_INT_INC,QFA_NP_BELONGTO_PARCOMSH,QFA_OTHER_COMPREH_INC,QFA_TOT_COMPREH_INC,QFA_TOT_COMPREH_INC_MIN_SHRHLDR,QFA_TOT_COMPREH_INC_PARENT_COMP'
    cols = 'QFA_TOT_OPER_REV,QFA_OPER_REV,QFA_INTEREST_INC,QFA_INSUR_PREM_UNEARNED,QFA_HANDLING_CHRG_COMM_INC,QFA_TOT_PREM_INC,QFA_REINSUR_INC,QFA_PREM_CEDED,QFA_UNEARNED_PREM_RSRV,QFA_NET_INC_AGENCY BUSINESS,QFA_NET_INC_UNDERWRITING-BUSINESS,QFA_NET_INC_CUSTOMERASSET-MANAGEMENT BUSINESS,QFA_OTHER_OPER_INC,QFA_NET_INT_INC,QFA_NET_FEE_AND_COMMISSION_INC,QFA_NET_OTHER_OPER_INC,QFA_TOT_OPER_COST,QFA_OPER_COST,QFA_GROSSMARGIN,QFA_INTEREST_EXP,QFA_HANDLING_CHRG_COMM_EXP,QFA_OPER_EXP,QFA_TAXES_SURCHARGES_OPS,QFA_SELLING_DIST_EXP,QFA_GERL_ADMIN_EXP,QFA_FIN_EXP_IS,QFA_IMPAIR_LOSS_ASSETS,QFA_PREPAY_SURR,QFA_NET_CLAIM_EXP,QFA_NET_INSUR_CONT_RSRV,QFA_DVD_EXP_INSURED,QFA_REINSURANCE_EXP,QFA_CLAIM_EXP_RECOVERABLE,QFA_INSUR_RSRV_RECOVERABLE,QFA_REINSUR_EXP_RECOVERABLE,QFA_OTHER_OPER_EXP,QFA_NET_GAIN_CHG_FV,QFA_NET_INVEST_INC,QFA_INC_INVEST_ASSOC_JV_ENTP,QFA_NET_GAIN_FX_TRANS,QFA_OPPROFIT,QFA_NON_OPER_REV,QFA_NON_OPER_EXP,QFA_NET_LOSS_DISP_NONCUR_ASSET,QFA_TOT_PROFIT,QFA_TAX,QFA_UNCONFIRMED_INVEST_LOSS_IS,QFA_NET_PROFIT_IS,QFA_MINORITY_INT_INC,QFA_NP_BELONGTO_PARCOMSH,QFA_OTHER_COMPREH_INC,QFA_TOT_COMPREH_INC,QFA_TOT_COMPREH_INC_MIN_SHRHLDR,QFA_TOT_COMPREH_INC_PARENT_COMP'
    
    for ss in cols.split(','):
        print("QFA_TOT_OPER_REV_R[\'" + ss +"_R\'] = " + "data[\'"+ss+"\'] / "+"data['QFA_TOT_OPER_REV']")
    
    
    QFA_TOT_OPER_REV_R = pd.DataFrame()
    QFA_TOT_OPER_REV_R['code'] = data['code'] 
    QFA_TOT_OPER_REV_R['rptDate'] = data['rptDate']
    
    QFA_TOT_OPER_REV_R['QFA_TOT_OPER_REV_R'] = data['QFA_TOT_OPER_REV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OPER_REV_R'] = data['QFA_OPER_REV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_INTEREST_INC_R'] = data['QFA_INTEREST_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_INSUR_PREM_UNEARNED_R'] = data['QFA_INSUR_PREM_UNEARNED'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_HANDLING_CHRG_COMM_INC_R'] = data['QFA_HANDLING_CHRG_COMM_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_PREM_INC_R'] = data['QFA_TOT_PREM_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_REINSUR_INC_R'] = data['QFA_REINSUR_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_PREM_CEDED_R'] = data['QFA_PREM_CEDED'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_UNEARNED_PREM_RSRV_R'] = data['QFA_UNEARNED_PREM_RSRV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INC_AGENCY BUSINESS_R'] = data['QFA_NET_INC_AGENCY BUSINESS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INC_UNDERWRITING-BUSINESS_R'] = data['QFA_NET_INC_UNDERWRITING-BUSINESS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INC_CUSTOMERASSET-MANAGEMENT BUSINESS_R'] = data['QFA_NET_INC_CUSTOMERASSET-MANAGEMENT BUSINESS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OTHER_OPER_INC_R'] = data['QFA_OTHER_OPER_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INT_INC_R'] = data['QFA_NET_INT_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_FEE_AND_COMMISSION_INC_R'] = data['QFA_NET_FEE_AND_COMMISSION_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_OTHER_OPER_INC_R'] = data['QFA_NET_OTHER_OPER_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_OPER_COST_R'] = data['QFA_TOT_OPER_COST'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OPER_COST_R'] = data['QFA_OPER_COST'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_GROSSMARGIN_R'] = data['QFA_GROSSMARGIN'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_INTEREST_EXP_R'] = data['QFA_INTEREST_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_HANDLING_CHRG_COMM_EXP_R'] = data['QFA_HANDLING_CHRG_COMM_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OPER_EXP_R'] = data['QFA_OPER_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TAXES_SURCHARGES_OPS_R'] = data['QFA_TAXES_SURCHARGES_OPS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_SELLING_DIST_EXP_R'] = data['QFA_SELLING_DIST_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_GERL_ADMIN_EXP_R'] = data['QFA_GERL_ADMIN_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_FIN_EXP_IS_R'] = data['QFA_FIN_EXP_IS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_IMPAIR_LOSS_ASSETS_R'] = data['QFA_IMPAIR_LOSS_ASSETS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_PREPAY_SURR_R'] = data['QFA_PREPAY_SURR'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_CLAIM_EXP_R'] = data['QFA_NET_CLAIM_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INSUR_CONT_RSRV_R'] = data['QFA_NET_INSUR_CONT_RSRV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_DVD_EXP_INSURED_R'] = data['QFA_DVD_EXP_INSURED'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_REINSURANCE_EXP_R'] = data['QFA_REINSURANCE_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_CLAIM_EXP_RECOVERABLE_R'] = data['QFA_CLAIM_EXP_RECOVERABLE'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_INSUR_RSRV_RECOVERABLE_R'] = data['QFA_INSUR_RSRV_RECOVERABLE'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_REINSUR_EXP_RECOVERABLE_R'] = data['QFA_REINSUR_EXP_RECOVERABLE'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OTHER_OPER_EXP_R'] = data['QFA_OTHER_OPER_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_GAIN_CHG_FV_R'] = data['QFA_NET_GAIN_CHG_FV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_INVEST_INC_R'] = data['QFA_NET_INVEST_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_INC_INVEST_ASSOC_JV_ENTP_R'] = data['QFA_INC_INVEST_ASSOC_JV_ENTP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_GAIN_FX_TRANS_R'] = data['QFA_NET_GAIN_FX_TRANS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OPPROFIT_R'] = data['QFA_OPPROFIT'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NON_OPER_REV_R'] = data['QFA_NON_OPER_REV'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NON_OPER_EXP_R'] = data['QFA_NON_OPER_EXP'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_LOSS_DISP_NONCUR_ASSET_R'] = data['QFA_NET_LOSS_DISP_NONCUR_ASSET'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_PROFIT_R'] = data['QFA_TOT_PROFIT'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TAX_R'] = data['QFA_TAX'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_UNCONFIRMED_INVEST_LOSS_IS_R'] = data['QFA_UNCONFIRMED_INVEST_LOSS_IS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NET_PROFIT_IS_R'] = data['QFA_NET_PROFIT_IS'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_MINORITY_INT_INC_R'] = data['QFA_MINORITY_INT_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_NP_BELONGTO_PARCOMSH_R'] = data['QFA_NP_BELONGTO_PARCOMSH'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_OTHER_COMPREH_INC_R'] = data['QFA_OTHER_COMPREH_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_COMPREH_INC_R'] = data['QFA_TOT_COMPREH_INC'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_COMPREH_INC_MIN_SHRHLDR_R'] = data['QFA_TOT_COMPREH_INC_MIN_SHRHLDR'] / data['QFA_TOT_OPER_REV']
    QFA_TOT_OPER_REV_R['QFA_TOT_COMPREH_INC_PARENT_COMP_R'] = data['QFA_TOT_COMPREH_INC_PARENT_COMP'] / data['QFA_TOT_OPER_REV']
    insert_record = json.loads(QFA_TOT_OPER_REV_R.to_json(orient='records'))
    ret = db.QFA_TOT_OPER_REV_R.insert_many(insert_record)
    print(ret)

if __name__ == "__main__":
    print('finished')